# Generated by Django 5.2.17 on 2026-09-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва матеріалу')),
                ('category', models.CharField(choices=[('flooring', 'Підлога та стяжка'), ('walls', 'Стіни та кладка'), ('plaster', 'Штукатурка та шпаклівка'), ('finishes', 'Оздоблення та фарбування'), ('consumables', 'Витратні матеріали та кріплення')], default='flooring', max_length=30, verbose_name='Категорія')),
                ('unit', models.CharField(help_text='м², мішок 25кг, упак, відро, шт, л', max_length=30, verbose_name='Одиниця виміру')),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний для розрахунків')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Ціна на матеріал',
                'verbose_name_plural': 'Каталог цін на матеріали',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наприклад: Квартира вул. Хрещатик 15, кв. 42', max_length=200, verbose_name="Назва проекту / об'єкта")),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Замовник / Клієнт')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон клієнта')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name="Адреса об'єкта")),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В роботі'), ('completed', 'Завершено'), ('archived', 'В архіві')], default='draft', max_length=20, verbose_name='Статус проекту')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки та коментарі виконроба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': "Будівельний об'єкт",
                'verbose_name_plural': 'Будівельні проекти',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_id', models.CharField(choices=[('laminate', 'Ламінат та паркетна дошка'), ('screed', 'Стяжка підлоги'), ('tile', 'Керамічна плитка та клей'), ('gasblock', 'Газобетонні блоки'), ('brick', 'Будівельна цегла'), ('plaster', 'Штукатурка стін'), ('putty', 'Шпаклівка стін та стелі'), ('primer', 'Ґрунтовка поверхонь'), ('paint', 'Фарба для стін і стелі'), ('wallpaper', 'Шпалери та клей')], max_length=50, verbose_name='Тип калькулятора')),
                ('title', models.CharField(help_text='Наприклад: Укладання ламінату у спальні', max_length=200, verbose_name='Назва розрахунку')),
                ('area', models.DecimalField(decimal_places=2, default=0, help_text='м² або м³', max_digits=8, verbose_name="Розрахункова площа / об'єм")),
                ('inputs_data', models.JSONField(blank=True, default=dict, verbose_name='Параметри розрахунку (JSON)')),
                ('materials_data', models.JSONField(blank=True, default=list, verbose_name='Специфікація матеріалів (JSON)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Орієнтовна вартість матеріалів (грн)')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки майстра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='estimates.project', verbose_name="Об'єкт / Проект")),
            ],
            options={
                'verbose_name': 'Кошторисний розрахунок',
                'verbose_name_plural': 'Збережені кошториси',
                'ordering': ['-created_at'],
            },
        ),
    ]
